package com.github.sladecek.maze.jmaze.app;

import com.github.sladecek.maze.jmaze.generator.DepthFirstMazeGenerator;
import com.github.sladecek.maze.jmaze.generator.IMazeGenerator;
import com.github.sladecek.maze.jmaze.generator.MazeRealization;
import com.github.sladecek.maze.jmaze.maze.IMaze;
import com.github.sladecek.maze.jmaze.maze.Irrengarten;
import com.github.sladecek.maze.jmaze.print2d.MazeOutputFormat;
import com.github.sladecek.maze.jmaze.print2d.SvgMazePrinter;
import com.github.sladecek.maze.jmaze.print3d.IMaze3DMapper;
import com.github.sladecek.maze.jmaze.print3d.Maze3DSizes;
import com.github.sladecek.maze.jmaze.print3d.ModelFromShapes;
import com.github.sladecek.maze.jmaze.print3d.PlanarMapper;
import com.github.sladecek.maze.jmaze.print3d.generic3dmodel.Model3d;
import com.github.sladecek.maze.jmaze.print3d.output.OpenScad3DPrinter;
import com.github.sladecek.maze.jmaze.print3d.output.StlMazePrinter;
import com.github.sladecek.maze.jmaze.print3d.output.ThreeJs3DPrinter;
import com.github.sladecek.maze.jmaze.printstyle.DefaultPrintStyle;
import com.github.sladecek.maze.jmaze.printstyle.IPrintStyle;
import com.github.sladecek.maze.jmaze.properties.MazeProperties;
import com.github.sladecek.maze.jmaze.rectangular.RectangularIrrengarten;
import com.github.sladecek.maze.jmaze.rectangular.RectangularMaze;
import com.github.sladecek.maze.jmaze.rectangular.TestAppRectangular;
import com.github.sladecek.maze.jmaze.shapes.ShapeContainer;
import com.github.sladecek.maze.jmaze.util.MazeGenerationException;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.Random;
import java.util.function.Supplier;
import java.util.logging.*;

/**
 * Generate any maze..
 */
public class TestApp {

    /**
     * Prints a maze generated by an external maze provider to a .jpg file.
     *
     * @param fileName     name of the output file.
     * @param mazeProvider external function that generates the maze.
     */
    public final void printTestMaze(final Supplier<IMaze> mazeProvider) {
        System.setProperty("java.util.logging.SimpleFormatter.format",
                "%5$s%n");
        LogManager.getLogManager().reset();
        LOG.setLevel(Level.INFO);
        try {
            // logging
            FileHandler fh = new FileHandler("maze.log");
            LOG.addHandler(fh);
            fh.setFormatter(new SimpleFormatter());
            // construct maze generator
            IMaze maze = mazeProvider.get();
            maze.buildMaze();

            final Random randomGenerator = new Random();
            randomGenerator.setSeed(0);
            IMazeGenerator g = new DepthFirstMazeGenerator(randomGenerator);

            // generate
            MazeRealization realization = g.generateMaze(maze.getGraph());
            ShapeContainer shapes = maze.getFlatModel().applyRealization(realization);

            final String fileName = "maze-" + maze.getName();
            // print 2D
            if (maze.canBePrintedIn2D()) {
                SvgMazePrinter printer = new SvgMazePrinter();

                FileOutputStream sSvg = new FileOutputStream(fileName + ".svg");
                printer.printShapes(shapes, MazeOutputFormat.svg, sSvg);
                FileOutputStream fPdf = new FileOutputStream(fileName+ ".pdf");
                printer.printShapes(shapes, MazeOutputFormat.pdf, fPdf);
            }

            IMaze3DMapper mapper = maze.create3DMapper();
            if (mapper != null) {
                // print 3D
                double approxRoomSizeInmm = 3;
                Maze3DSizes sizes = new Maze3DSizes();

                IPrintStyle colors = new DefaultPrintStyle();

             //   mapper.configureAltitudes(sizes);
                Model3d model = ModelFromShapes.make(shapes, mapper, sizes, colors);
                System.out.println(model);

                final boolean printInJs = false;
                final boolean printInScad = true;
                final boolean printStl = true;


                if (printInJs) {
                    FileOutputStream fJs = new FileOutputStream(fileName + ".js");
                    new ThreeJs3DPrinter().printModel(model, fJs);
                    fJs.close();
                }
                if (printInScad) {
                    FileOutputStream fScad = new FileOutputStream(fileName + ".scad");
                    new OpenScad3DPrinter().printModel(model, fScad);
                    fScad.close();
                }
                if (printStl) {
                    FileOutputStream fStl = new FileOutputStream(fileName + ".stl");
                    new StlMazePrinter().printModel(model, fStl);
                    fStl.close();
                }
            }
        } catch (SecurityException | IOException | MazeGenerationException e) {
            e.printStackTrace();
        }
    }

    /**
     * Logging facility.
     */
    private static final Logger LOG = Logger.getLogger("maze");

    public static void main(String[] args) {
        new TestApp().printTestMaze( () -> {

            IMaze m = new RectangularMaze();
            MazeProperties p = m.getDefaultProperties();
            p.put("width", 2);
            p.put("height", 2);
            m.setProperties(p);
            return m;
        });
    }

}
